# -*- yaml -*-
version: 2.1
orbs:
  go-module: timakin/go-module@0.3.0
  sixrs-gke: sixriversystems/sixrs-gke@0.1.1
jobs:
  build:
    docker:
      - image: docker:18.09.9-git
    steps:
      - checkout
      - setup_remote_docker
      - docker build -t arm64 -f cross.dockerfile .
      - docker run --name temp-container arm64 /bin/true
      - docker cp temp-container:build/stage/sqlite3/v4.1.0/node-v64-linux-arm64.tar.gz ./
      - docker rm temp-container
      - ls -la
workflows:
  build_and_release:
    jobs:
      - build:
          context: 6rs-circle

      
